CREATE OR REPLACE PROCEDURE SUPERVISOR_TOTAL_REVENUE
(
  VAR_IS_FOREIGN IN NUMBER
, VAR_REVENUE OUT NUMBER
) AS
BEGIN
  SELECT SUM(CASE WHEN CAR.IS_FOREIGN = 1 THEN SERVICE.COST_FOREIGN ELSE SERVICE.COST_OUR END) AS COST
  INTO VAR_REVENUE
  FROM "CARS" CAR
  INNER JOIN "WORKS" JOB ON JOB.CAR_ID = CAR.ID
  INNER JOIN "SERVICES" SERVICE ON JOB.SERVICE_ID = SERVICE.ID
  WHERE CAR.IS_FOREIGN = VAR_IS_FOREIGN
;
END SUPERVISOR_TOTAL_REVENUE;