CREATE OR REPLACE FUNCTION SUPERVISOR_TOP_MASTERS RETURN SYS_REFCURSOR AS
  masters_cursor SYS_REFCURSOR;
BEGIN
  OPEN masters_cursor FOR
    SELECT MST.*, SUM(1) AS JOBSCOUNT
    FROM "MASTERS" MST
    INNER JOIN "WORKS" JOB ON JOB.MASTER_ID = MST.ID
    GROUP BY MST.ID, MST.NAME
    ORDER BY JOBSCOUNT DESC;
  RETURN masters_cursor;
END SUPERVISOR_TOP_MASTERS;