CREATE OR REPLACE TRIGGER TRIGGER_CARS_NUMBER_UNIQUENESS
BEFORE INSERT OR UPDATE ON CARS FOR EACH ROW
DECLARE
  cars_count NUMBER;
BEGIN
  SELECT COUNT(1)
  INTO cars_count
  FROM CARS CAR
  WHERE CAR.NUM = :new.NUM;

  IF cars_count > 0 THEN RAISE_APPLICATION_ERROR(-20001, 'CAR with the same license plate already exists'); END IF;

END;