CREATE OR REPLACE TRIGGER TRIGGER_WORKS_DATE
BEFORE INSERT OR UPDATE ON WORKS
FOR EACH ROW
BEGIN
  IF :new.DATE_WORK > CURRENT_DATE THEN RAISE_APPLICATION_ERROR(-20002, 'DATE_WORK is from the future'); END IF;
END;